---
deployment:
  tasks:
    - export DEPLOYPATH=/home/usebyvll/public_html
    - /bin/cp -f index.html datenschutz.html support.html script.js blade-icon.png .htaccess "$DEPLOYPATH/"
    - /bin/mkdir -p "$DEPLOYPATH/screens"
    - /bin/cp -f screens/*.png "$DEPLOYPATH/screens/"
